blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/klaptafel/ha-package-tracker-card/discussions
    about: For general questions that aren't a bug report
